"""empty message

Revision ID: 066d769bdea8
Revises: 1cdc6c17b219
Create Date: 2021-05-02 20:21:10.394831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '066d769bdea8'
down_revision = '1cdc6c17b219'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'goal_id')
    op.drop_table('goal')
    # ### end Alembic commands ###
