"""empty message

Revision ID: 27845567a643
Revises: 6262ac7b68f5
Create Date: 2021-05-02 22:45:11.621391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27845567a643'
down_revision = '6262ac7b68f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.drop_constraint('task_Goal_fkey', 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['id'])
    op.drop_column('task', 'Goal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('Goal', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key('task_Goal_fkey', 'task', 'goal', ['Goal'], ['id'])
    op.drop_column('task', 'goal_id')
    # ### end Alembic commands ###
