"""empty message

Revision ID: 6262ac7b68f5
Revises: d050fcaf971c
Create Date: 2021-05-02 22:42:59.385492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6262ac7b68f5'
down_revision = 'd050fcaf971c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
